import { Booking } from "./booking";

export const negCellCodes: Booking[] = [
  {
    Test: "1",
    Arrival: new Date("11-Jan-24"),
    Nights: 2,
    Property: "LEIFOR",
    CellCode: "TSTBB",
    Rooms: 1,
    Adults: 2,
    Children: 0,
    Cot: "No",
    Disabled: "No",
    Double: "Yes",
    CardType: "VI",
    CreditCard: "4128 0031 4829 5531",
    ExpiryDate: "Jul-24",
    GuestTitle: "Mr",
    GuestInitial: "K",
    GuestSurname: "Tester",
    Address1: "1 The High Street",
    PostCode: "AA1 1AA",
    Telephone: "0208 123 4567",
    EmailAddress: "test@whitbread.com",
    BookingCompanyName: "SIMARD",
    doNotCancelAfter: true,
  },
  {
    Test: "2",
    Arrival: new Date("11-Jan-24"),
    Nights: 3,
    Property: "GATMTI",
    CellCode: "TSTRO",
    Rooms: 1,
    Adults: 1,
    Children: 0,
    Cot: "No",
    Disabled: "No",
    Double: "Yes",
    CardType: "VI",
    CreditCard: "4128 0031 4829 5531",
    ExpiryDate: "Jul-24",
    GuestTitle: "Mrs",
    GuestInitial: "R",
    GuestSurname: "Green",
    Address1: "1 The High Street",
    PostCode: "AA1 1AA",
    Telephone: "0208 123 4567",
    EmailAddress: "test@whitbread.com",
    BookingCompanyName: "SIMARD",
    doNotCancelAfter: true,
  },
  {
    Test: "3",
    Arrival: new Date("11-Jan-24"),
    Nights: 1,
    Property: "LONGOO",
    CellCode: "TSTHB",
    Rooms: 1,
    Adults: 1,
    Children: 0,
    Cot: "No",
    Disabled: "No",
    Double: "Yes",
    CardType: "VI",
    CreditCard: "4128 0031 4829 5531",
    ExpiryDate: "Jul-24",
    GuestTitle: "Mr",
    GuestInitial: "U",
    GuestSurname: "Pink",
    Address1: "1 The High Street",
    PostCode: "AA1 1AA",
    Telephone: "0208 123 4567",
    EmailAddress: "test@whitbread.com",
    BookingCompanyName: "SIMARD",
    doNotCancelAfter: true,
  },
  {
    Test: "4",
    Arrival: new Date("11-Jan-24"),
    Nights: 1,
    Property: "MUNCIT",
    CellCode: "TSTRO",
    Rooms: 1,
    Adults: 1,
    Children: 1,
    Cot: "No",
    Disabled: "No",
    Double: "No",
    CardType: "AM",
    CreditCard: "3707 7777 0000 771",
    ExpiryDate: "May-27",
    GuestTitle: "Mrs",
    GuestInitial: "E",
    GuestSurname: "Grey",
    Address1: "1 The High Street",
    PostCode: "AA1 1AA",
    Telephone: "0208 123 4567",
    EmailAddress: "test@whitbread.com",
    BookingCompanyName: "SIMARD",
    doNotCancelAfter: true,
  },
];
