import os
from dotenv import load_dotenv

load_dotenv()

# Get the key
def get_key(key_name):
    return os.getenv(key_name)

# Database
MONGODB_DATABASE_URI = get_key('MONGO_URI')

# Infura parameters
INFURA_WSS_ENDPOINT = get_key('INFURA_WSS_ENDPOINT')
INFURA_PROJECT_ID = get_key('INFURA_PROJECT_ID')
INFURA_PROJECT_SECRET = get_key('INFURA_PROJECT_SECRET')

# Transferwise parameters
TRANSFERWISE_API_ENDPOINT = get_key('TRANSFERWISE_API_ENDPOINT')
TRANSFERWISE_API_TOKEN = get_key('TRANSFERWISE_API_TOKEN')
TRANSFERWISE_PROFILE_ID = get_key('TRANSFERWISE_PROFILE_ID')

# Stripe parameters
STRIPE_API_KEY = get_key('STRIPE_API_KEY')
STRIPE_WEBHOOK_SECRET = get_key('STRIPE_WEBHOOK_SECRET')

# Circle Parameters
CIRCLE_API_ENDPOINT = get_key('CIRCLE_API_ENDPOINT')
CIRCLE_API_KEY = get_key('CIRCLE_API_KEY')
CIRCLE_WALLET_ADDRESS = get_key('CIRCLE_WALLET_ADDRESS')
USDC_CONTRACT = get_key('USDC_CONTRACT')
USDC_DECIMALS = get_key('USDC_DECIMALS')

# Simard parameters
ORGID_CONTRACT = get_key('ORGID_CONTRACT')
ORGIDVALIDATOR_URL = get_key('ORGIDVALIDATOR_URL')
ORGIDVALIDATOR_V2_URL = get_key('ORGIDVALIDATOR_V2_URL')
ORGID_VALIDATION_DISABLED = get_key('ORGID_VALIDATION_DISABLED') == "TRUE"


PAYMENT_MANAGER_CONTRACT = get_key('PAYMENT_MANAGER_CONTRACT')
VIRTUAL_CARD_ORGID = get_key('SIMARD_ORGID')
SIMARD_ORGID = get_key('SIMARD_ORGID')
SIMARD_ORGID_CHAINID = get_key('SIMARD_ORGID_CHAINID')
GLIDER_OTA_ORGID = get_key('GLIDER_OTA_ORGID')
GLIDER_B2B_ORGID = get_key('GLIDER_B2B_ORGID')
VIRTUAL_CARD_DETAILS = get_key('VIRTUAL_CARD_DETAILS')
ENABLE_SIMULATED_DEPOSIT = get_key('ENABLE_SIMULATED_DEPOSIT') == "TRUE"

# Elastic Search
ELASTIC_SEARCH_URL = get_key('ELASTIC_SEARCH_URL')

# Redis Memcache
REDIS_URL = get_key('REDIS_URL')

# PCI-Proxy
PCIPROXY_API_USERNAME = get_key('PCIPROXY_API_USERNAME')
PCIPROXY_API_PASSWORD = get_key('PCIPROXY_API_PASSWORD')
PCIPROXY_API_TOKEN = get_key('PCIPROXY_API_TOKEN')
PCIPROXY_API_SERVICES_URL = get_key('PCIPROXY_API_SERVICES_URL')
PCIPROXY_API_PULL_URL = get_key('PCIPROXY_API_PULL_URL')
PCIPROXY_API_TOKENIZE_URL = get_key('PCIPROXY_API_TOKENIZE_URL')
PCIPROXY_API_3DS_URL = get_key('PCIPROXY_API_3DS_URL')

# Datatrans
DATATRANS_TOKENIZE_URL = get_key('DATATRANS_TOKENIZE_URL')

# AMEX Setup
AMEX_HOST = get_key("AMEX_HOST")
AMEX_PORT = get_key("AMEX_PORT") or "443"
AMEX_SMART_TOKENS_ENDPOINT = get_key("AMEX_SMART_TOKENS_ENDPOINT")
AMEX_CLIENT_ID = get_key("AMEX_CLIENT_ID")
AMEX_CLIENT_SECRET = get_key("AMEX_CLIENT_SECRET")
AMEX_BILLING_ACCOUNT_ID = get_key("AMEX_BILLING_ACCOUNT_ID")
OVERRIDE_AMEX_TOKEN = get_key("OVERRIDE_AMEX_TOKEN") == "TRUE"
TADC_REPORT_API_ENABLED = get_key("TADC_REPORT_API_ENABLED") == "TRUE"
AMEX_SKIP_PCIPROXY = get_key("AMEX_SKIP_PCIPROXY") == "TRUE"