export const amenitiesMap = {
  "1": "Adjoining rooms",
  "2": "Air conditioning",
  "3": "Alarm clock",
  "4": "All news channel",
  "5": "AM/FM radio",
  "6": "Baby listening device",
  "7": "Balcony/Lanai/Terrace",
  "8": "Barbeque grills",
  "9": "Bath tub with spray jets",
  "10": "Bathrobe",
  "11": "Bathroom amenities",
  "12": "Bathroom telephone",
  "13": "Bathtub",
  "14": "Bathtub only",
  "15": "Bathtub/shower combination",
  "16": "Bidet",
  "17": "Bottled water",
  "18": "Cable television",
  "19": "Coffee/Tea maker",
  "20": "Color television",
  "21": "Computer",
  "22": "Connecting rooms",
  "23": "Converters/ Voltage adaptors",
  "24": "Copier",
  "25": "Cordless phone",
  "26": "Cribs",
  "27": "Data port",
  "28": "Desk",
  "29": "Desk with lamp",
  "30": "Dining guide",
  "31": "Direct dial phone number",
  "32": "Dishwasher",
  "33": "Double beds",
  "34": "Dual voltage outlet",
  "35": "Electrical current voltage",
  "36": "Ergonomic chair",
  "37": "Extended phone cord",
  "38": "Fax machine",
  "39": "Fire alarm",
  "40": "Fire alarm with light",
  "41": "Fireplace",
  "42": "Free toll free calls",
  "43": "Free calls",
  "44": "Free credit card access calls",
  "45": "Free local calls",
  "46": "Free movies/video",
  "47": "Full kitchen",
  "48": "Grab bars in bathroom",
  "49": "Grecian tub",
  "50": "Hairdryer",
  "51": "High speed internet connection",
  "52": "Interactive web TV",
  "53": "International direct dialing",
  "54": "Internet access",
  "55": "Iron",
  "56": "Ironing board",
  "57": "Whirpool",
  "58": "King bed",
  "59": "Kitchen",
  "60": "Kitchen supplies",
  "61": "Kitchenette",
  "62": "Knock light",
  "63": "Laptop",
  "64": "Large desk",
  "65": "Large work area",
  "66": "Laundry basket/clothes hamper",
  "67": "Loft",
  "68": "Microwave",
  "69": "Minibar",
  "70": "Modem",
  "71": "Modem jack",
  "72": "Multi-line phone",
  "73": "Newspaper",
  "74": "Non-smoking",
  "75": "Notepads",
  "76": "Office supplies",
  "77": "Oven",
  "78": "Pay per view movies on TV",
  "79": "Pens",
  "80": "Phone in bathroom",
  "81": "Plates and bowls",
  "82": "Pots and pans",
  "83": "Prayer mats",
  "84": "Printer",
  "85": "Private bathroom",
  "86": "Queen bed",
  "87": "Recliner",
  "88": "Refrigerator",
  "89": "Refrigerator with ice maker",
  "90": "Remote control television",
  "91": "Rollaway bed",
  "92": "Safe",
  "93": "Scanner",
  "94": "Separate closet",
  "95": "Separate modem line available",
  "96": "Shoe polisher",
  "97": "Shower only",
  "98": "Silverware/utensils",
  "99": "Sitting area",
  "100": "Smoke detectors",
  "101": "Smoking",
  "102": "Sofa bed",
  "103": "Speaker phone",
  "104": "Stereo",
  "105": "Stove",
  "106": "Tape recorder",
  "107": "Telephone",
  "108": "Telephone for hearing impaired",
  "109": "Telephones with message light",
  "110": "Toaster oven",
  "111": "Trouser/Pant press",
  "112": "Turn down service",
  "113": "Twin bed",
  "114": "Vaulted ceilings",
  "115": "VCR movies",
  "116": "VCR player",
  "117": "Video games",
  "118": "Voice mail",
  "119": "Wake-up calls",
  "120": "Water closet",
  "121": "Water purification system",
  "122": "Wet bar",
  "123": "Wireless internet connection",
  "124": "Wireless keyboard",
  "125": "Adaptor available for telephone PC use",
  "126": "Air conditioning individually controlled in room",
  "127": "Bathtub &whirlpool separate",
  "128": "Telephone with data ports",
  "129": "CD  player",
  "130": "Complimentary local calls time limit",
  "131": "Extra person charge for rollaway use",
  "132": "Down/feather pillows",
  "133": "Desk with electrical outlet",
  "134": "ESPN available",
  "135": "Foam pillows",
  "136": "HBO available",
  "137": "High ceilings",
  "138": "Marble bathroom",
  "139": "List of movie channels available",
  "140": "Pets allowed",
  "141": "Oversized bathtub",
  "142": "Shower",
  "143": "Sink in-room",
  "144": "Soundproofed room",
  "145": "Storage space",
  "146": "Tables and chairs",
  "147": "Two-line phone",
  "148": "Walk-in closet",
  "149": "Washer/dryer",
  "150": "Weight scale",
  "151": "Welcome gift",
  "152": "Spare electrical outlet available at desk",
  "153": "Non-refundable charge for pets",
  "154": "Refundable deposit for pets",
  "155": "Separate tub and shower",
  "156": "Entrance type to guest room",
  "157": "Ceiling fan",
  "158": "CNN available",
  "159": "Electrical adaptors available",
  "160": "Buffet breakfast",
  "161": "Accessible room",
  "162": "Closets in room",
  "163": "DVD player",
  "164": "Mini-refrigerator",
  "165": "Separate line billing for multi-line phone",
  "166": "Self-controlled heating/cooling system",
  "167": "Toaster",
  "168": "Analog data port",
  "169": "Collect calls",
  "170": "International calls",
  "171": "Carrier access",
  "172": "Interstate calls",
  "173": "Intrastate calls",
  "174": "Local calls",
  "175": "Long distance calls",
  "176": "Operator-assisted calls",
  "177": "Credit card access calls",
  "178": "Calling card calls",
  "179": "Toll free calls",
  "180": "Universal AC/DC adaptors",
  "181": "Bathtub seat",
  "182": "Canopy/poster bed",
  "183": "Cups/glassware",
  "184": "Entertainment center",
  "185": "Family/oversized room",
  "186": "Hypoallergenic bed",
  "187": "Hypoallergenic pillows",
  "188": "Lamp",
  "189": "Meal included - breakfast",
  "190": "Meal included - continental breakfast",
  "191": "Meal included - dinner",
  "192": "Meal included - lunch",
  "193": "Shared bathroom",
  "194": "Telephone TDD/Textphone",
  "195": "Water bed",
  "196": "Extra adult charge",
  "197": "Extra child charge",
  "198": "Extra child charge for rollaway use",
  "199": "Meal included:  full American breakfast",
  "200": "Futon",
  "201": "Murphy bed",
  "202": "Tatami mats",
  "203": "Single bed",
  "204": "Annex room",
  "205": "Free newspaper",
  "206": "Honeymoon suites",
  "207": "Complimentary high speed internet in room",
  "208": "Maid service",
  "209": "PC hook-up in room",
  "210": "Satellite television",
  "211": "VIP rooms",
  "212": "Cell phone recharger",
  "213": "DVR player",
  "214": "iPod docking station",
  "215": "Media center",
  "216": "Plug & play panel",
  "217": "Satellite radio",
  "218": "Video on demand",
  "219": "Exterior corridors",
  "220": "Gulf view",
  "221": "Accessible room",
  "222": "Interior corridors",
  "223": "Mountain view",
  "224": "Ocean view",
  "225": "High speed internet access fee",
  "226": "High speed wireless",
  "227": "Premium movie channels",
  "228": "Slippers",
  "229": "First nighters' kit",
  "230": "Chair provided with desk",
  "231": "Pillow top mattress",
  "232": "Feather bed",
  "233": "Duvet",
  "234": "Luxury linen type",
  "235": "International channels",
  "236": "Pantry",
  "237": "Dish-cleaning supplies",
  "238": "Double vanity",
  "239": "Lighted makeup mirror",
  "240": "Upgraded bathroom amenities",
  "241": "VCR player available at front desk",
  "242": "Instant hot water",
  "243": "Outdoor space",
  "244": "Hinoki tub",
  "245": "Private pool",
  "246": "High Definition (HD) Flat Panel Television  - 32 inches or greater",
  "247": "Room windows open",
  "248": "Bedding type unknown or unspecified",
  "249": "Full bed",
  "250": "Round bed",
  "251": "TV",
  "252": "Child rollaway",
  "253": "DVD player available at front desk",
  "254": "Video game player:",
  "255": "Video game player available at front desk",
  "256": "Dining room seats",
  "257": "Full size mirror",
  "258": "Mobile/cellular phones",
  "259": "Movies",
  "260": "Multiple closets",
  "261": "Plates/glassware",
  "262": "Safe large enough to accommodate a laptop",
  "263": "Bed linen thread count",
  "264": "Blackout curtain",
  "265": "Bluray player",
  "266": "Device with mp3",
  "267": "No adult channels or adult channel lock",
  "268": "Non-allergenic room",
  "269": "Pillow type",
  "270": "Seating area with sofa/chair",
  "271": "Separate toilet area",
  "272": "Web enabled",
  "273": "Widescreen TV",
  "274": "Other data connection",
  "275": "Phoneline billed separately",
  "276": "Separate tub or shower",
  "277": "Video games",
  "278": "Roof ventilator",
  "279": "Children's playpen",
  "280": "Plunge pool",
  "281": "DVD movies",
  "282": "Air filtration",
  "283": "Exercise Equipment in Room",
  "284": "Wrapped coffee and condiments packages",
  "285": "TV remotes disinfected",
  "286": "Extraneous room amenities removed",
  "287": "Electronics controlled by personal mobile device",
  "288": "TV controlled by personal mobile device",
  "289": "Voice enabled room controls",
  "290": "Room air purification system",
  "291": "Allergy friendly room",
  "292": "Medical grade air purification system",
  "293": "All surfaces sanitized between stays",
  "294": "TV has connection for external devices",
  "295": "Streaming services supported",
  "296": "In room workout program",
};

export type AmenitiesCode = keyof typeof amenitiesMap;
