export const unitsOfMeasureMap = {
  "1": "Miles",
  "2": "Kilometers",
  "3": "Meters",
  "4": "Millimeters",
  "5": "Centimeters",
  "6": "Yards",
  "7": "Feet",
  "8": "Inches",
  "9": "Pixels",
  "10": "Block",
  "11": "Megabytes",
  "12": "Gigabytes",
  "13": "Square feet",
  "14": "Square meters",
  "15": "Pounds",
  "16": "Kilograms",
  "17": "Square inch",
  "18": "Square yard",
  "19": "Acre",
  "20": "Square millimeter",
  "21": "Square centimeter",
  "22": "Hectare",
  "23": "Ounce",
  "24": "Gram",
  "25": "Gallons",
  "26": "Liters",
  "27": "Kilowatts",
  "28": "Cubic meters",
};

export type UnitsOfMeasureCode = keyof typeof unitsOfMeasureMap;
