export enum HttpStatusCode {
    OK= 200,
    // Client errors (4xx statuses)
    CLIENT_BAD_REQUEST= 400,
    CLIENT_UNAUTHORIZED= 401,
    CLIENT_PAYMENT_REQUIRED= 402,
    CLIENT_FORBIDDEN= 403,
    CLIENT_NOT_FOUND= 404,
    CLIENT_REQUEST_TIMEOUT= 408,
    // Server errors (5xx statuses)
    SERVER_INTERNAL_SERVER_ERROR= 500,
    SERVER_NOT_IMPLEMENTED= 501,
    SERVER_SERVICE_NOT_AVAILABLE= 503,
    SERVER_GATEWAY_TIMEOUT= 504,
}
